- name: Deploy to Kubernetes with Minikube
  hosts: localhost
  vars:
    minikube_home: "{{ lookup('env', 'WORKSPACE') }}"
  tasks:

    - name: Delete Minikube cluster if exists
      shell: minikube delete
      ignore_errors: yes

    - name: Create ~/.kube and ~/.minikube directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ minikube_home }}/.kube"
        - "{{ minikube_home }}/.minikube"

    - name: Set environment variables for Minikube
      set_fact:
        minikube_env:
          MINIKUBE_HOME: "{{ minikube_home }}"
          KUBECONFIG: "{{ minikube_home }}/.kube/config"

    # - name: Disable fs.protected_regular to allow locking temp files
    #   become: yes
    #   command: sysctl fs.protected_regular=0

    - name: Start Minikube using Docker driver
      environment: "{{ minikube_env }}"
      shell: |
        minikube start --driver=docker --install-addons=true --delete-on-failure

    - name: Enable Ingress addon in Minikube
      environment: "{{ minikube_env }}"
      shell: minikube addons enable ingress

    - name: Wait for ingress-nginx-controller pod to be ready
      environment: "{{ minikube_env }}"
      shell: |
        minikube kubectl -- wait --namespace ingress-nginx \
        --for=condition=ready pod \
        --selector=app.kubernetes.io/component=controller \
        --timeout=120s

    - name: Apply all secrets
      environment: "{{ minikube_env }}"
      shell: minikube kubectl -- apply -f ./kube/secret

    - name: Apply all Kubernetes manifests from ./k8s directory
      environment: "{{ minikube_env }}"
      shell: minikube kubectl -- apply -f ./kube

    - name: Reminder to export KUBECONFIG manually
      debug:
        msg: |
          To access kubectl from your shell, run:
          export KUBECONFIG={{ minikube_home }}/.kube/config