- name: Deploy to Kubernetes using existing Minikube
  hosts: localhost
  vars:
    # This should point to where Jenkins can access kubeconfig & minikube profiles
    minikube_home: "/var/lib/jenkins"

  tasks:
    - name: Set environment variables for kubectl
      set_fact:
        minikube_env:
          KUBECONFIG: "{{ minikube_home }}/.kube/config"

    - name: Apply all secrets
      environment: "{{ minikube_env }}"
      shell: kubectl apply -f ./kube/secret

    - name: Apply all Kubernetes manifests from ./kube directory
      environment: "{{ minikube_env }}"
      shell: kubectl apply -f ./kube

    - name: Reminder to export KUBECONFIG manually (for manual use)
      debug:
        msg: |
          To access kubectl from your shell, run:
          export KUBECONFIG={{ minikube_home }}/.kube/config
