# playbook.yaml
- name: Apply Kubernetes Manifests with Existing Minikube
  hosts: localhost
  remote_user: manu
  vars:
    kubeconfig_path: "{{ lookup('env', 'KUBECONFIG') | default('~/.kube/config', true) }}"
  tasks:
    - name: Check if kubectl is available
      command: kubectl version --client
      register: kubectl_check
      failed_when: kubectl_check.rc != 0
      changed_when: false

    - name: Apply all secrets
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      shell: kubectl apply -f ./kube/secret

    - name: Apply all Kubernetes manifests
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      shell: kubectl apply -f ./kube
