apiVersion: batch/v1
kind: CronJob
metadata:
  name: api-fetcher-cron
spec:
  schedule: "0 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: api-fetcher
            image: api-fetcher:v1
            imagePullPolicy: IfNotPresent
            env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
            - name: DB_HOST
              value: "postgres-service"
          restartPolicy: OnFailure
