apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aqi-ingress

spec:
  rules:
  - host: aqi.spe
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 80
